name: QA Automation Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest-playwright allure-pytest requests pymysql flask
          playwright install --with-deps chromium

      - name: Run smoke tests
        run: pytest tests/ api/test_users_api.py -v -m smoke

      - name: Run regression tests
        run: pytest tests/ api/test_users_api.py -v -m regression
